---
- name: Criar usuario local e adicionar ao Administrators
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuarioansible }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:

    - name: Criar usuario local
      ansible.windows.win_user:
        name: "{{ usuario }}"
        password: "{{ senha }}"
        state: present
        password_never_expires: yes

    - name: Adicionar ao grupo Administrators
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - "{{ usuario }}"
        state: present
