---
- name: Atualizar repositórios e sistema no CentOS
  hosts: all
  become: yes
  tasks:
    - name: Comentar linhas mirrorlist nos arquivos de repositório
      ansible.builtin.shell: |
        sed -i 's/^mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/CentOS-*.repo

    - name: Alterar baseurl para apontar para o vault
      ansible.builtin.shell: |
        sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo

    - name: Limpar cache do yum
      ansible.builtin.shell: yum clean all

    - name: Recriar cache do yum
      ansible.builtin.shell: yum makecache

    - name: Atualizar open-vm-tools
      ansible.builtin.shell: yum -y install open-vm-tools
