- name: Listar hosts com observIQ instalado
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Verificar observIQ no registro
      win_shell: |
        $paths = @(
          "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
          "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
        )

        foreach ($p in $paths) {
          Get-ItemProperty $p -ErrorAction SilentlyContinue |
          Where-Object { $_.DisplayName -eq "observIQ Distro for OpenTelemetry Collector" } |
          Select-Object -ExpandProperty DisplayName
        }
      register: observiq_check
      changed_when: false

    - name: Resultado
      debug:
        msg: >
          {{ inventory_hostname }} {{
          'INSTALADO' if observiq_check.stdout_lines | length > 0
          else 'NADA'
          }}
