- name: Playbook para Windows via WinRM
  hosts: all
  gather_facts: false
  vars:
    ansible_port: 5985 
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'

  tasks:
    - name: Criar diretório C:\Temp\iza
      win_file:
        path: C:\Temp\iza
        state: directory
