---
- name: Criar diretório no host remoto
  hosts: all
  become: yes
  tasks:
    - name: Criar diretório /tmp/meu_diretorio
      file:
        path: /tmp/meu_diretorio
        state: directory
        mode: '0755'
        owner: root
        group: root
