
- name: Playbook Windows com Kerberos
  hosts: all
  gather_facts: no

  pre_tasks:
    - name: Executar kinit com senha
      ansible.builtin.shell: |
        echo "{{ ansible_password }}" | kinit -V {{ ansible_user }}
      register: kinit_out
      no_log: false
      failed_when: "'Password incorrect' in kinit_out.stderr"

    - name: Verificar ticket Kerberos com klist
      ansible.builtin.shell: klist
      register: klist_out
      changed_when: false

    - name: Mostrar ticket Kerberos
      debug:
        var: klist_out.stdout_lines

  tasks:
    - name: Testar comunicação com host Windows
      ansible.windows.win_ping:
