- name: Remover observIQ Distro for OpenTelemetry Collector
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Buscar GUID do observIQ pelo nome completo
      win_shell: |
        $paths = @(
          "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
          "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
        )

        foreach ($p in $paths) {
          Get-ItemProperty $p -ErrorAction SilentlyContinue |
          Where-Object { $_.DisplayName -eq "observIQ Distro for OpenTelemetry Collector" } |
          Select-Object -First 1 -ExpandProperty PSChildName
        }
      register: observiq_guid
      changed_when: false

    - name: Remover observIQ
      win_package:
        product_id: "{{ observiq_guid.stdout }}"
        state: absent
        arguments: /qn
      when: observiq_guid.stdout | length > 0



