---
- name: Remover observiq otel collector (multi-distro)
  hosts: all
  become: true

  tasks:

    - name: Parar e desabilitar o serviço observiq-otel-collector
      systemd:
        name: observiq-otel-collector
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remover pacote (todas as distros)
      package:
        name: observiq-otel-collector
        state: absent

    - name: Purge do pacote (somente Debian/Ubuntu)
      apt:
        name: observiq-otel-collector
        state: absent
        purge: true
      when: ansible_os_family == "Debian"

    - name: Remover diretório /opt/observiq-otel-collector
      file:
        path: /opt/observiq-otel-collector
        state: absent

    - name: Reload systemd
      command: systemctl daemon-reload

