- name: Remover observIQ Distro for OpenTelemetry Collector
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Remover observIQ pelo nome do pacote
      win_package:
        name: "observIQ Distro for OpenTelemetry Collector"
        state: absent
        arguments: /qn


