- name: Remover observIQ Distro for OpenTelemetry Collector
  hosts: windows
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Verificar se o observIQ está instalado
      win_package_facts:
      register: pkg_facts

    - name: Remover observIQ Distro for OpenTelemetry Collector
      win_package:
        product_id: "{{ item.product_id }}"
        state: absent
      loop: "{{ pkg_facts.packages }}"
      when: "'observIQ Distro for OpenTelemetry Collector' in item.name"
