- name: Remover observIQ Distro for OpenTelemetry Collector
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Procurar observIQ via WMI
      win_shell: |
        Get-WmiObject -Class Win32_Product |
        Where-Object { $_.Name -like "*observIQ*" } |
        Select-Object IdentifyingNumber, Name
      register: observiq_pkg

    - name: Remover observIQ
      win_package:
        product_id: "{{ item.IdentifyingNumber }}"
        state: absent
      loop: "{{ observiq_pkg.stdout_lines | map('from_json') | list }}"
      when: observiq_pkg.stdout != ""
