- name: Remover observIQ Distro for OpenTelemetry Collector
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ usuario }}"
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Buscar GUID do observIQ no registro
      win_shell: |
        $paths = @(
          "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
          "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
        )

        foreach ($p in $paths) {
          Get-ItemProperty $p -ErrorAction SilentlyContinue |
          Where-Object { $_.DisplayName -eq "observIQ Distro for OpenTelemetry Collector" } |
          Select-Object -ExpandProperty PSChildName
        }
      register: observiq_guid
      changed_when: false

    - name: Exibir GUIDs encontrados
      debug:
        msg: "observIQ encontrado com GUID(s): {{ observiq_guid.stdout_lines }}"
      when: observiq_guid.stdout_lines | length > 0

    - name: Remover observIQ
      win_package:
        product_id: "{{ item }}"
        state: absent
        arguments: /qn
      loop: "{{ observiq_guid.stdout_lines }}"
      when:
        - observiq_guid.stdout_lines is defined
        - observiq_guid.stdout_lines | length > 0
